<?php
/* @var $escaper \Magento\Framework\Escaper */
?>

<div class="admin__aw-block-title">
    <div class="block-title">
        <span class="title"><?= $escaper->escapeHtml(__("Your store is 
        ready to be viewed on mobile.")) ?></span>
        <span class="title"><?= $escaper->escapeHtml(__("Just download application 
        and use serial number code to enter and preview your store.")) ?></span>
    </div>
</div>
