<div class="mobile-logo-boxes-container">
    <div class="mobile-connector-play-store-box">
    	<a target="_blank" href='<?= $block::APP_STORE_URL?>'>
        	<img width="150" src='<?= $this->getViewFileUrl('Aheadworks_MobileAppConnector::images/apple_store.jpg') ?>' alt="<?= __("App store") ?>">
        </a>
    </div>

    <div class="mobile-connector-play-store-box">
    	<a target="_blank" href='<?= $block::PLAY_STORE_URL?>'>
        	<img width="150" src='<?= $this->getViewFileUrl('Aheadworks_MobileAppConnector::images/google_play.png') ?>' alt="<?= __("Google App store") ?>">
   		</a>
    </div>
</div>