<?php
/* @var $block \Aheadworks\MobileAppConnector\Block\Adminhtml\OverView\StoreLogo */
/* @var $escaper \Magento\Framework\Escaper */
?>

<div class="mobile-logo-boxes-container">
    <div class="admin__fieldset">
        <div class="admin__field">
            <div class="admin__field-label">
                <?= $escaper->escapeHtml(__("Preview on iOS:")) ?>
                <div class="admin__field-note">
                    <span><?= $escaper->escapeHtml(__("To download from the App store scan QR code:")) ?></span>
                </div>
            </div>
            <div class="admin__field-control">
                <a target="_blank" href='<?= $escaper->escapeUrl($block::APP_STORE_URL) ?>'>
                    <?php $qrCode = $block::QR_CODE_IMAGE_URL; ?>
                    <img 
                    src='<?= $escaper->escapeUrl($block->getViewFileUrl('Aheadworks_MobileAppConnector::'.$qrCode)) ?>' 
                    alt="<?= $escaper->escapeHtml(__("App store")) ?>">
                </a>
                <button title="Copy Link" type="button" class="action-default"  id="myappstoreurl">
                    <span>copy link</span>
                </button>
                <input type="text" value="<?= $escaper->escapeUrl($block::APP_STORE_URL) ?>" id="appstoreurl" />
            </div>
        </div>
    </div>
    <div class="admin__fieldset">
        <div class="admin__field">
            <div class="admin__field-label">
                <?= $escaper->escapeHtml(__("Preview on Android:")) ?>
            <div class="admin__field-note">
                <span><?= $escaper->escapeHtml(__("To download from the Google Play store scan QR code:")) ?></span>
            </div>
            </div>
            <div class="admin__field-control">
                <a target="_blank" href='<?= $escaper->escapeUrl($block::PLAY_STORE_URL) ?>'>
                    <img 
                    src='<?= $escaper->escapeUrl($block->getViewFileUrl('Aheadworks_MobileAppConnector::'.$qrCode)) ?>' 
                    alt="<?= $escaper->escapeHtml(__("Google App store.")) ?>">
                </a>
                <button title="Copy Link" type="button" class="action-default" id="mygoogleappurl">
                    <span>copy link</span>
                </button>
                <input type="text" value="<?= $escaper->escapeUrl($block::PLAY_STORE_URL) ?>" id="googleappurl" />
            </div>
        </div>
    </div>
</div>