<?php
/** @var $block \Aheadworks\MobileAppConnector\Block\Adminhtml\OverView\StoreLogo */
/** @var $escaper \Magento\Framework\Escaper */
// @codingStandardsIgnoreFile

?>
<div class="mobile-logo-boxes-container">
    <div class="mobile-connector-play-store-box">
    	<a target="_blank" href='<?= $escaper->escapeUrl($block::APP_STORE_URL) ?>'>
        	<img src='<?= $escaper->escapeUrl($block->getViewFileUrl('Aheadworks_MobileAppConnector::images/app-store.png')) ?>' alt="<?= $escaper->escapeHtml(__("App store")) ?>">
        </a>
    </div>
    <div class="mobile-connector-play-store-box">
    	<a target="_blank" href='<?= $escaper->escapeUrl($block::PLAY_STORE_URL) ?>'>
        	<img src='<?= $escaper->escapeUrl($block->getViewFileUrl('Aheadworks_MobileAppConnector::images/google-play.png')) ?>' alt="<?= $escaper->escapeHtml(__("Google App store.")) ?>">
   		</a>
    </div>
</div>
